FROM nginx:latest

RUN apt-get update && \
    apt-get install -y \
    docker.io \
    curl

COPY ./misc/nginx.conf /etc/nginx/nginx.conf

RUN echo '#!/bin/sh \n \
cat /logs/test.log > /usr/share/nginx/html/index.html 2>&1 \n \
service nginx start \
' > entrypoint.sh && \
    chmod +x entrypoint.sh

EXPOSE 80

ENTRYPOINT [ "./entrypoint.sh" ] 