apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: test-repo-app
      image: 703lovelost/test-repo-app
      volumeMounts:
        - mountPath: /logs
          name: logs-volume
  restartPolicy: Never
  volumes:
    - name: logs-volume
      persistentVolumeClaim:
        claimName: logs-pvc
